version: "3.8"
services:
  mongo:
    container_name: sender-mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sender_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    volumes:
      - ./mongo/volumes:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - sender
  redis:
    container_name: sender-redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass root_password
    volumes:
      - ./redis/volumes:/data
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - sender
  app:
    container_name: sender-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    hostname: app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    networks:
      - sender
networks:
  sender:
    driver: bridge
